### ISSUE TITLE
Install file

### ISSUE THREAD

**Issue by kgassel** [T800G/OfficeScroll#1]
Hello, where is the install.bat file you mention?

**Comment by tullydwyer** [comment]
Luckily I found the GitHub from the following website.

Compiled files here:
http://free-sk.t-com.hr/T800soft/software/OfficeScroll.html

**Comment by sollyucko** [comment]
`install.bat` is in [the releases](https://github.com/T800G/OfficeScroll/releases).

**Comment by T800G** [comment]
Release zip package contains all necessary files.
