### ISSUE TITLE
Unable to fully remove from Office 2016

### ISSUE THREAD

**Issue by Greco92** [T800G/OfficeScroll#10]
Running REMOVE.bat and restarted but still getting "MsoScroll64.dll file not found", wanted to remove it as it it was no longer working after recent updates, see this issue , https://github.com/T800G/OfficeScroll/issues/8.

![EXCEL_2019-04-16_10-46-46](https://user-images.githubusercontent.com/28339294/56178530-30d04700-6035-11e9-939b-c1f79165cacf.png)
https://i.imgur.com/TsW8hYn.png

**Comment by T800G** [comment]
Excel and Word must be closed before file can be removes.
