### ISSUE TITLE
PPT and Onenote needs this function too!

### ISSUE THREAD

**Issue by Pegasus-work** [T800G/OfficeScroll#13]
first i want to thank the author for fixing the problem that perplex me a long time, and i really want to use this fuction in PPT and Onenote, too. If it can be repaired, i will thank you very much.

**Comment by T800G** [comment]
OneNote doesn't support programmatic scroll.

**Comment by T800G** [comment]
Updated latest release package.
PowerPoint add-in is provided in a separate zip package because Kaspersky antivirus software causes PowerPoint to crash when loading ppa/ppm add-ins.
