### ISSUE TITLE
shift+scroll triggers `Alt` key displaying ribbon shortcuts Key Tips

### ISSUE THREAD

**Issue by shenghxie** [T800G/OfficeScroll#18]
### Steps to reproduce
1. Shift + scroll wheel

### Expected results
1. Excel scroll horizontally
2. not trigger ribbon shortcut key tips

### Actual results
1. Excel scroll horizontally ok
2. also trigger ribbon shortcut key tips

### Environment
Windows 10
Office version 16.0.12527.21230 32-bit

### Additional information
Ribbon shortcut key tips are the letters in small images next to the tabs and options.

**Comment by shenghxie** [comment]
Downgrading to v1.0 release and the key tips went away.
Both 1.2.7075.35530 and 1.2.6773.29897 have the same issue.

**Comment by huangtaizia** [comment]
I have an issue: Cannot generate formula to anothers cells (quick copy formula from cell) on Excel 2016
