### ISSUE TITLE
July 2018 commits causing Excel Key Tips to toggle

### ISSUE THREAD

**Issue by NicketyNickNick** [T800G/OfficeScroll#7]
After installing (from here: http://free-sk.t-com.hr/T800soft/software/OfficeScroll.html), while using Excel 2013 x64 version:
When holding the shift key, and then scrolling with the mouse wheel the Excel Key Tips toggle on/off, making scrolling jagged, and causing other issues.

Link to download a video showing this behavior is here (but expires on 10/3/2018): [https://wetransfer.com/downloads/483de1b99efb3ecd8a823efc02484f7220180926190528/1da4fced0b3d482fda7865f585d4fc9d20180926190529/bbd787](url)

**Comment by TomW1605** [comment]
i get exactly the same issue

**Comment by NicketyNickNick** [comment]
I've also noticed that this seems to occur more often if i scroll slowly, like one scroll-wheel click at a time, or hold the shift key a bit long after scrolling.

**Comment by TomW1605** [comment]
for me it happens every time i just move 1 click. i use a Logitech G502 mouse and i have configured the sideways scroll to scroll with the shift key. it presses the shift key, scrolls, waits 20ms then releases the shift key. it repeats after 40ms if i am still holding the scroll wheel. it also flashes every loop

**Comment by T800G** [comment]
Fixed.
