### ISSUE TITLE
Changing Keyboard Language on scroll

### ISSUE THREAD

**Issue by kiavash17** [T800G/OfficeScroll#9]
Hi great utility and it works great, but if I have a second language installed, keyboard language will be switched unexpectedly while scrolling.

**Comment by jonstrutz11** [comment]
Having the same issue as OP

**Comment by martinmego** [comment]
I'm experiencing the same issue.

Windows 10, Excel for Office 365 MSO (16.0.11328.20390) 64-bit

Installed keyboards:
German, Russian, English, Czech, Chinese (Taiwan)

Every time I shift-scroll in Excel, it switches keyboard language.

**Comment by T800G** [comment]
This addin sends additional Alt key strokes to hide ribbon tooltips.
If you use multiple system input languages, set the input language switch key to "Not assigned" (Control panel -> Regional settings) and enable language bar in taskbar to switch languages through right-click on it.
